# Generated by Django 4.0.6 on 2023-05-19 18:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import post.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('None', 'None'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Brown', 'Brown'), ('Black', 'Black')], default='None', help_text='Flair color.', max_length=6)),
                ('text', models.CharField(help_text='Flair message.', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(help_text='Date and time the post was created.')),
                ('message', models.TextField(help_text='Post content.', max_length=1000)),
                ('fire_index', models.IntegerField(default=0, help_text='Net change to score over the past day. Used to sort by "hotness".')),
                ('author', models.ForeignKey(default=None, help_text='User that made the post.', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='post_user', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
                ('downvotes', models.ManyToManyField(help_text='Users who have downvoted this post.', related_name='post_downvoters', to=settings.AUTH_USER_MODEL)),
                ('flair', models.ForeignKey(blank=True, help_text='Optional post flair.', null=True, on_delete=django.db.models.deletion.CASCADE, to='post.flair')),
                ('upvotes', models.ManyToManyField(help_text='Users who have upvoted this post.', related_name='post_upvoters', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, post.mixins.SubmissionMixin),
        ),
        migrations.CreateModel(
            name='EmbeddedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('post', models.ForeignKey(help_text='Image embedded in post content.', on_delete=django.db.models.deletion.CASCADE, to='post.post', validators=[django.core.validators.validate_image_file_extension])),
            ],
        ),
    ]
