# Generated by Django 4.0.6 on 2023-05-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the community.', max_length=64)),
                ('private', models.BooleanField(default=False, help_text='Specifies if a community is invite-only.')),
                ('member_only', models.BooleanField(default=False, help_text='Specifies if users must be a member to post.')),
                ('description', models.TextField(blank=True, help_text='Community description.', max_length=300, null=True)),
            ],
        ),
    ]
