# Generated by Django 4.0.6 on 2023-05-19 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Comment content.', max_length=200)),
                ('fire_index', models.IntegerField(default=0, help_text='Net change to score over the past day. Used to sort by "hotness".')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
                ('downvotes', models.ManyToManyField(help_text='Users who have downvoted this comment.', related_name='comment_downvoters', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='comment.comment')),
                ('upvotes', models.ManyToManyField(help_text='Users who have upvoted this comment.', related_name='comment_upvoters', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, post.mixins.SubmissionMixin),
        ),
    ]
